### ISSUE TITLE
Add some utility CSS for hiding/showing elements

### ISSUE THREAD

**Issue by oliverklee** [oliverklee/ext-onetimeaccount#621]
```css
.tx-onetimeaccount-display-block {
    display: block;
}

.tx-onetimeaccount-display-none {
    display: none;
}
```
